---
- hosts: front
  vars:
    project: TestPROJ
    version: 1.4.5
    env: staging
    pubsub_password: pikachu
  remote_user: xav
  tasks:
  - name: deploy it
    git: repo=https://github.com/xleliberty/ansible-deploytest.git dest=/home/xav/deploytest

  - name: notify progress
    uri: url=https://eliberty-hubot.herokuapp.com/publish
      method=POST HEADER_Content-Type="application/x-www-form-urlencoded"
      body="passwd={{pubsub_password}}&event=deploy.progress&data=Notify progress one"
  - name: notify progress2
    uri: url=https://eliberty-hubot.herokuapp.com/publish
      method=POST HEADER_Content-Type="application/x-www-form-urlencoded"
      body="passwd={{pubsub_password}}&event=deploy.progress&data=Notify progress two"

  - name: world notifier
    uri: url=https://eliberty-hubot.herokuapp.com/hubot/elib-deploy?environment={{env}}&project={{project}}&version={{version}}
      method=GET
